use crate::codec::codec_trait::TfCodec;
use crate::structures::s_type::StructureType;
use crate::structures::traffic_proc::TrafficProcessorHolder;
use crate::structures::transport::Transport;
use bytes::Bytes;
use futures_util::future::BoxFuture;
use std::net::SocketAddr;
use std::sync::Arc;
use tokio::sync::oneshot::Sender;
use tokio_util::bytes::BytesMut;
use tokio_util::codec::Framed;

/// The future returned by a route's [`ServeFn`].
///
/// It resolves to a tuple containing:
/// - `Result<Bytes, Bytes>`: The response payload to send back to the client (`Ok`) or an error payload (`Err`).
/// - `Option<Sender<(AcceptFn<S, C>, Arc<S>)>>`: An optional oneshot sender. If returned, it signals
///   the server to hand off the underlying raw stream to the provided [`AcceptFn`] for manual processing.
pub type ServeFuture<S, C> = BoxFuture<
    'static,
    (Result<Bytes, Bytes>, Option<Sender<(AcceptFn<S, C>, Arc<S>)>>),
>;

/// The future returned by a stream handoff handler ([`AcceptFn`]).
/// It runs asynchronously after the server has yielded ownership of the raw connection.
pub type AcceptFuture = BoxFuture<'static, ()>;

/// The function signature for a standard route handler.
///
/// A `ServeFn` processes an incoming framed message and returns a [`ServeFuture`].
/// It is typically generated by the `#[serve]` macro.
///
/// # Arguments
/// * `state: Arc<S>` - The shared application state.
/// * `addr: SocketAddr` - The remote address of the connected client.
/// * `route_tx: Option<Sender<...>>` - A oneshot channel sender. Passing an [`AcceptFn`]
///   and state through this channel requests the server to yield ownership of the raw TCP/WebSocket stream
///   to your handler (stream handoff).
/// * `s_type: Box<dyn StructureType>` - The structure type tag of the incoming message, used for deserialization.
/// * `data: BytesMut` - The raw payload of the message.
pub type ServeFn<S, C> = fn(
    Arc<S>,
    SocketAddr,
    Option<Sender<(AcceptFn<S, C>, Arc<S>)>>,
    Box<dyn StructureType>,
    BytesMut,
) -> ServeFuture<S, C>;

/// The function signature for a stream handoff handler.
///
/// This function is invoked when a [`ServeFn`] requests to take manual ownership of the underlying connection
/// via the `route_tx` channel. It allows you to bypass the standard request/response routing and interact
/// directly with the raw `Framed` transport (e.g., for protocol upgrades, proxying, or continuous streaming).
/// It is typically generated by the `#[accept]` macro.
///
/// # Arguments
/// * `state: Arc<S>` - The shared application state.
/// * `addr: SocketAddr` - The remote address of the connected client.
/// * `stream_and_holder: (Framed<Transport, C>, TrafficProcessorHolder<C>)` - The raw framed connection
///   and a holder for managing ongoing traffic metrics/processing.
pub type AcceptFn<S, C> =
fn(Arc<S>, SocketAddr, (Framed<Transport, C>, TrafficProcessorHolder<C>)) -> AcceptFuture;

/// Represents a single route in the server's router.
///
/// A `Route` binds a specific application state (`S`) and a codec (`C`) to a handler function ([`ServeFn`]).
/// Routes are typically created using the `#[serve]` macro and then registered with the `TfServerRouter`.
///
/// # Type Parameters
/// * `S` - The global application state structure, which must be `Send + Sync + 'static`.
/// * `C` - The codec used for framing and optionally encrypting the connection (must implement [`TfCodec`]).
pub struct Route<S, C>
where
    S: Send + Sync + 'static,
    C: TfCodec,
{
    /// The shared application state passed to the handler.
    pub state: Arc<S>,

    /// The handler function invoked for every incoming message routed to this path.
    pub serve: ServeFn<S, C>,
}